Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -446,39 +446,40 @@ jobs:
         shell: bash
         working-directory: kernel
         run: |
-         set -e
+          set -e
 
-         echo "===== CLEAN SOURCE ====="
+          echo "======================================"
+          echo "BUILD WHYRED KERNEL"
+          echo "======================================"
 
-         rm -rf .config
-         rm -rf include/config
-         rm -rf include/generated
-         rm -rf arch/arm64/include/generated
-         rm -rf include2
+          mkdir -p "$BUILD_DIR"
 
-         echo "===== DEFCONFIG ====="
+          echo "===== USING EXISTING CONFIG ====="
 
-         make ARCH=arm64 \
-         CROSS_COMPILE=aarch64-linux-gnu- \
-         CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
-         CC=clang \
-         LLVM=1 \
-         LLVM_IAS=1 \
-         whyred_defconfig
+          test -f "$BUILD_DIR/.config" || {
+            echo "ERROR: $BUILD_DIR/.config tidak ditemukan!"
+            exit 1
+          }
 
-         echo "===== BUILD ====="
+          grep -E '^CONFIG_(KSU|OVERLAY_FS|KALLSYMS)=' \
+            "$BUILD_DIR/.config" || true
 
-         make -j"$(nproc)" \
-         ARCH=arm64 \
-         CROSS_COMPILE=aarch64-linux-gnu- \
-         CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
-         CC=clang \
-         LLVM=1 \
-         LLVM_IAS=1
+          echo "===== BUILD ====="
 
-         echo "===== BUILD SUCCESS ====="
+          make -j"$(nproc)" \
+            O="$BUILD_DIR" \
+            ARCH=arm64 \
+            CROSS_COMPILE="$CROSS_COMPILE" \
+            CROSS_COMPILE_ARM32="$CROSS_COMPILE_ARM32" \
+            CC=clang \
+            LLVM=1 \
+            LLVM_IAS=1 \
+            KCFLAGS="$KCFLAGS" \
+            V=1
 
-         ls -lh arch/arm64/boot/
+          echo "===== BUILD SUCCESS ====="
+
+          ls -lah "$BUILD_DIR/arch/arm64/boot/"
 
       # ============================================================
       # LZ4HC OPTIONAL
