Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1388,15 +1388,43 @@ jobs:
         run: |
           ccache -s || true
 
+      - name: Prepare kernel image
+        run: |
+         set -e
+
+         mkdir -p kernel-output
+
+         if [ -f "$BUILD_DIR/arch/arm64/boot/Image.gz-dtb" ]; then
+         cp "$BUILD_DIR/arch/arm64/boot/Image.gz-dtb" \
+         kernel-output/Image.gz-dtb
+
+         elif [ -f "$BUILD_DIR/arch/arm64/boot/Image.gz" ]; then
+         cp "$BUILD_DIR/arch/arm64/boot/Image.gz" \
+         kernel-output/Image.gz
+
+         elif [ -f "$BUILD_DIR/arch/arm64/boot/Image" ]; then
+         cp "$BUILD_DIR/arch/arm64/boot/Image" \
+         kernel-output/Image
+
+         else
+         echo "ERROR: Kernel image tidak ditemukan!"
+         exit 1
+         fi
+
+         cp "$BUILD_DIR/.config" \
+         kernel-output/kernel.config
+
+         echo "=== KERNEL OUTPUT ==="
+         ls -lh kernel-output
+
       # ============================================================
       # UPLOAD IMAGE
       # ============================================================
       - name: Upload kernel image
         uses: actions/upload-artifact@v4
         with:
-          name: SPECTRA-Kernel-Image
+          name: kernel-image
           path: kernel-output/Image
-          if-no-files-found: error
 
       # ============================================================
       # UPLOAD ANYKERNEL3 ZIP
